
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AS_KEYWORD CITY_KEYWORD COLON COMMA CREATE_KEYWORD ENDFOR_KEYWORD EOF FOR_KEYWORD LPAREN LSQUAREPAREN MAP_KEYWORD MOUNTAIN_KEYWORD NEWLINE NUMBER ON_KEYWORD PLACE_KEYWORD RENDER_KEYWORD RIVER_KEYWORD ROAD_KEYWORD RPAREN RSQUAREPAREN STRING TERRAIN_KEYWORD VARNAME_ARGNAMEstart : instruction_iterator EOFinstruction_iterator : instruction_iterator instruction NEWLINEinstruction_iterator : emptyinstruction : CREATE_KEYWORD type VARNAME_ARGNAME construction_argumentsinstruction : PLACE_KEYWORD type construction_arguments ON_KEYWORD VARNAME_ARGNAME coordinatesinstruction : PLACE_KEYWORD type VARNAME_ARGNAME construction_arguments ON_KEYWORD VARNAME_ARGNAME coordinatesinstruction : PLACE_KEYWORD VARNAME_ARGNAME ON_KEYWORD VARNAME_ARGNAME coordinatesinstruction : RENDER_KEYWORD VARNAME_ARGNAME optional_render_string optional_coordinatesinstruction : FOR_KEYWORD VARNAME_ARGNAME coordinates NEWLINE instruction_iterator ENDFOR_KEYWORDoptional_render_string : AS_KEYWORD STRING\n                              | emptyoptional_coordinates : coordinates\n                            | emptytype : MAP_KEYWORD\n            | TERRAIN_KEYWORD\n            | CITY_KEYWORD\n            | ROAD_KEYWORD\n            | RIVER_KEYWORD\n            | MOUNTAIN_KEYWORDconstruction_arguments : LPAREN argument_iterator RPARENargument_iterator : argument\n                         | argument_iterator COMMA argument\n                         | emptyargument : VARNAME_ARGNAME COLON valuevalue : NUMBER\n             | STRING\n             | list\n             | coordinatesvalue : VARNAME_ARGNAMElist : LSQUAREPAREN list_item_iterator RSQUAREPARENlist_item_iterator : value\n                          | list_item_iterator COMMA value\n                          | emptycoordinates : LPAREN value COMMA value RPARENempty :'
    
_lr_action_items = {'EOF':([0,2,3,10,],[-35,4,-3,-2,]),'CREATE_KEYWORD':([0,2,3,10,44,58,],[-35,6,-3,-2,-35,6,]),'PLACE_KEYWORD':([0,2,3,10,44,58,],[-35,7,-3,-2,-35,7,]),'RENDER_KEYWORD':([0,2,3,10,44,58,],[-35,8,-3,-2,-35,8,]),'FOR_KEYWORD':([0,2,3,10,44,58,],[-35,9,-3,-2,-35,9,]),'$end':([1,4,],[0,-1,]),'ENDFOR_KEYWORD':([3,10,44,58,],[-3,-2,-35,67,]),'NEWLINE':([5,20,27,29,30,32,40,41,42,43,54,57,63,67,71,72,],[10,-35,-35,-11,44,-4,-8,-12,-13,-10,-20,-7,-5,-9,-6,-34,]),'MAP_KEYWORD':([6,7,],[12,12,]),'TERRAIN_KEYWORD':([6,7,],[13,13,]),'CITY_KEYWORD':([6,7,],[14,14,]),'ROAD_KEYWORD':([6,7,],[15,15,]),'RIVER_KEYWORD':([6,7,],[16,16,]),'MOUNTAIN_KEYWORD':([6,7,],[17,17,]),'VARNAME_ARGNAME':([7,8,9,11,12,13,14,15,16,17,18,25,26,31,33,51,53,55,56,59,70,],[19,20,21,22,-14,-15,-16,-17,-18,-19,24,38,39,50,52,50,64,38,50,50,50,]),'LPAREN':([12,13,14,15,16,17,18,20,21,22,24,27,29,31,39,43,51,52,56,59,64,70,],[-14,-15,-16,-17,-18,-19,25,-35,31,25,25,31,-11,31,31,-10,31,31,31,31,31,31,]),'ON_KEYWORD':([19,23,34,54,],[26,33,53,-20,]),'AS_KEYWORD':([20,],[28,]),'RPAREN':([25,35,36,37,46,47,48,49,50,65,66,68,69,72,],[-35,54,-21,-23,-25,-26,-27,-28,-29,-22,-24,72,-30,-34,]),'COMMA':([25,35,36,37,45,46,47,48,49,50,51,60,61,62,65,66,69,72,73,],[-35,55,-21,-23,59,-25,-26,-27,-28,-29,-35,70,-31,-33,-22,-24,-30,-34,-32,]),'STRING':([28,31,51,56,59,70,],[43,47,47,47,47,47,]),'NUMBER':([31,51,56,59,70,],[46,46,46,46,46,]),'LSQUAREPAREN':([31,51,56,59,70,],[51,51,51,51,51,]),'COLON':([38,],[56,]),'RSQUAREPAREN':([46,47,48,49,50,51,60,61,62,69,72,73,],[-25,-26,-27,-28,-29,-35,69,-31,-33,-30,-34,-32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'instruction_iterator':([0,44,],[2,58,]),'empty':([0,20,25,27,44,51,],[3,29,37,42,3,62,]),'instruction':([2,58,],[5,5,]),'type':([6,7,],[11,18,]),'construction_arguments':([18,22,24,],[23,32,34,]),'optional_render_string':([20,],[27,]),'coordinates':([21,27,31,39,51,52,56,59,64,70,],[30,41,49,57,49,63,49,49,71,49,]),'argument_iterator':([25,],[35,]),'argument':([25,55,],[36,65,]),'optional_coordinates':([27,],[40,]),'value':([31,51,56,59,70,],[45,61,66,68,73,]),'list':([31,51,56,59,70,],[48,48,48,48,48,]),'list_item_iterator':([51,],[60,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> instruction_iterator EOF','start',2,'p_start','map_maker.py',334),
  ('instruction_iterator -> instruction_iterator instruction NEWLINE','instruction_iterator',3,'p_instruction_iterator','map_maker.py',340),
  ('instruction_iterator -> empty','instruction_iterator',1,'p_instruction_iterator_end','map_maker.py',347),
  ('instruction -> CREATE_KEYWORD type VARNAME_ARGNAME construction_arguments','instruction',4,'p_instruction_create','map_maker.py',353),
  ('instruction -> PLACE_KEYWORD type construction_arguments ON_KEYWORD VARNAME_ARGNAME coordinates','instruction',6,'p_instruction_place_new_unnamed','map_maker.py',363),
  ('instruction -> PLACE_KEYWORD type VARNAME_ARGNAME construction_arguments ON_KEYWORD VARNAME_ARGNAME coordinates','instruction',7,'p_instruction_place_new_named','map_maker.py',374),
  ('instruction -> PLACE_KEYWORD VARNAME_ARGNAME ON_KEYWORD VARNAME_ARGNAME coordinates','instruction',5,'p_instruction_place_existing','map_maker.py',386),
  ('instruction -> RENDER_KEYWORD VARNAME_ARGNAME optional_render_string optional_coordinates','instruction',4,'p_instruction_render','map_maker.py',396),
  ('instruction -> FOR_KEYWORD VARNAME_ARGNAME coordinates NEWLINE instruction_iterator ENDFOR_KEYWORD','instruction',6,'p_instruction_for','map_maker.py',406),
  ('optional_render_string -> AS_KEYWORD STRING','optional_render_string',2,'p_optional_render_string','map_maker.py',416),
  ('optional_render_string -> empty','optional_render_string',1,'p_optional_render_string','map_maker.py',417),
  ('optional_coordinates -> coordinates','optional_coordinates',1,'p_optional_coordinates','map_maker.py',426),
  ('optional_coordinates -> empty','optional_coordinates',1,'p_optional_coordinates','map_maker.py',427),
  ('type -> MAP_KEYWORD','type',1,'p_type','map_maker.py',436),
  ('type -> TERRAIN_KEYWORD','type',1,'p_type','map_maker.py',437),
  ('type -> CITY_KEYWORD','type',1,'p_type','map_maker.py',438),
  ('type -> ROAD_KEYWORD','type',1,'p_type','map_maker.py',439),
  ('type -> RIVER_KEYWORD','type',1,'p_type','map_maker.py',440),
  ('type -> MOUNTAIN_KEYWORD','type',1,'p_type','map_maker.py',441),
  ('construction_arguments -> LPAREN argument_iterator RPAREN','construction_arguments',3,'p_construction_arguments','map_maker.py',447),
  ('argument_iterator -> argument','argument_iterator',1,'p_argument_iterator','map_maker.py',453),
  ('argument_iterator -> argument_iterator COMMA argument','argument_iterator',3,'p_argument_iterator','map_maker.py',454),
  ('argument_iterator -> empty','argument_iterator',1,'p_argument_iterator','map_maker.py',455),
  ('argument -> VARNAME_ARGNAME COLON value','argument',3,'p_argument','map_maker.py',469),
  ('value -> NUMBER','value',1,'p_value','map_maker.py',475),
  ('value -> STRING','value',1,'p_value','map_maker.py',476),
  ('value -> list','value',1,'p_value','map_maker.py',477),
  ('value -> coordinates','value',1,'p_value','map_maker.py',478),
  ('value -> VARNAME_ARGNAME','value',1,'p_value_VARNAME','map_maker.py',482),
  ('list -> LSQUAREPAREN list_item_iterator RSQUAREPAREN','list',3,'p_list','map_maker.py',488),
  ('list_item_iterator -> value','list_item_iterator',1,'p_list_item_iterator','map_maker.py',494),
  ('list_item_iterator -> list_item_iterator COMMA value','list_item_iterator',3,'p_list_item_iterator','map_maker.py',495),
  ('list_item_iterator -> empty','list_item_iterator',1,'p_list_item_iterator','map_maker.py',496),
  ('coordinates -> LPAREN value COMMA value RPAREN','coordinates',5,'p_coordinates','map_maker.py',508),
  ('empty -> <empty>','empty',0,'p_empty','map_maker.py',514),
]
